name: Theneo API Documentation
description: Generate Stripe-like API Documentation
branding:
  icon: "award"
  color: "green"
inputs:
  PATH:
    description: "file path"
    required: true
  PROJECT_KEY:
    description: "project key"
    required: true
  SECRET:
    description: "github secret key"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
