name: Theneo API Documentation
description: Generate Stripe-like API Documentation
inputs:
  PATH:
    description: "API documentation file path"
    required: true
  PROJECT_KEY:
    description: "Unique Key for the project"
    required: true
  SECRET:
    description: "API Key from Theneo website"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "book-open"
  color: "orange"
